// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBoLRkZzpFRlmGo0rYxZmQtyBPA9aNQjYM",
    authDomain: "gunadarma-pos-marketplace.firebaseapp.com",
    projectId: "gunadarma-pos-marketplace",
    storageBucket: "gunadarma-pos-marketplace.firebasestorage.app",
    messagingSenderId: "410635663253",
    appId: "1:410635663253:web:24d960f24f6acf1899a89c",
  measurementId: "G-ZB3RZ8ZDTG"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7QUD_E5bgcBCukHmEhaCd-VpSCMca9Kg',
    appId: 'gunadarma-pos-marketplace',
    messagingSenderId: '410635663253',
    projectId: '1:410635663253:android:384eb100bef8f64c99a89c',
    storageBucket: 'gunadarma-pos-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.ppsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.ppsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBoLRkZzpFRlmGo0rYxZmQtyBPA9aNQjYM",
    authDomain: "gunadarma-pos-marketplace.firebaseapp.com",
    projectId: "gunadarma-pos-marketplace",
    storageBucket: "gunadarma-pos-marketplace.firebasestorage.app",
    messagingSenderId: "410635663253",
    appId: "1:410635663253:web:ff2d419db6af737999a89c",
    measurementId: "G-QJXMMF6S9Q"
  );
}
